name: Sync to Hugging Face hub

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Set Git identity
        run: |
          git config --global user.email "naufalnashif.imanuddin@gmail.com"
          git config --global user.name "naufalnashif"

      - name: Add Hugging Face remote and push
        env:
          HF_DEMO: ${{ secrets.HF_DEMO }}
        run: |
          git remote add hf https://naufalnashif:$HF_DEMO@huggingface.co/spaces/naufalnashif/demo-streamlit-eval-genai
          git push --force hf master:main
