name: Sync to Hugging Face hub

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set Git identity
        run: |
          git config --global user.email "naufalnashif.imanuddin@gmail.com"
          git config --global user.name "naufalnashif"

      - name: Add Hugging Face remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://naufalnashif:$HF_TOKEN@huggingface.co/spaces/naufalnashif/rfojk-streamlit-ai-eval

      - name: Push LFS objects to HF
        run: git lfs push --all hf main

      - name: Push branch to HF
        run: git push --force hf master:main
