[theme]
base = "light"
primaryColor = "#e74c3c"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#ffffff"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"
displayEnabled = true

[logger]
level = "debug"
messageFormat = "%(asctime)s — %(message)s"